from pathlib import Path
import json
r=Path.cwd();p=r/'source/rendering/scene_surface.cpp';t=p.read_text()
def replace(a,b):
    global t
    assert a in t,a;t=t.replace(a,b)
replace('#include "scene_chart.hpp"','#include "scene_chart.hpp"\n#include "scene_image.hpp"')
replace('std::map<std::string,History> histories;','std::map<std::string,History> histories;std::unique_ptr<SceneImages> images;')
replace('if(!ok){closed=true;histories.clear();','if(!ok){closed=true;images->clear();histories.clear();')
replace('void shut(const char* why){histories.clear();','void shut(const char* why){images->clear();histories.clear();')
replace('auto next=std::make_unique<SurfaceFrame>();','images->prepare(config);\n        auto next=std::make_unique<SurfaceFrame>();')
replace('const bool table=kind=="table";','const bool table=kind=="table",image=kind=="image";')
replace('need(bound||table||kind=="text"||kind=="group"','need(bound||table||image||kind=="text"||kind=="group"')
replace('}else out=text(w,nullptr);\n            text_bytes+=surface_text_bytes(out);need(text_bytes<=262144,"surface.capacity");','}else if(image){out.id=w["id"];out.kind=kind;}else out=text(w,nullptr);')
replace('auto raster=chart?raster_chart','auto raster=image?images->raster(w,q,out):chart?raster_chart')
replace('texts.emplace(out.id,std::move(out));','text_bytes+=surface_text_bytes(out);need(text_bytes<=262144,"surface.capacity");\n            texts.emplace(out.id,std::move(out));')
replace('std::function<bool()> clear_native):impl_','std::function<bool()> clear_native,std::string image_worker):impl_')
replace('i.authority=std::move(authority);','i.images=std::make_unique<SceneImages>(std::move(image_worker));i.authority=std::move(authority);')
replace('if(!i.start(now))return;i.histories.clear();','if(!i.start(now))return;i.images->clear();i.histories.clear();')
replace('SurfaceStatus SceneSurface::status()const','bool SceneSurface::poll_image_jobs(){auto& i=*impl_;i.owner();try{return i.images->poll();}catch(const Error&){i.images->clear(true);i.erase();i.status={SurfaceCode::alternative,0,0,"surface.capacity"};return true;}}\nSurfaceStatus SceneSurface::status()const')
replace('if(!i.allowed()){i.histories.clear();','if(!i.allowed()){i.images->clear();i.histories.clear();')
replace('i.config.authored.settings["display"]["enabled"].get<bool>()))i.status={SurfaceCode::empty,0,0,{}};','i.config.authored.settings["display"]["enabled"].get<bool>())){i.images->clear();i.status={SurfaceCode::empty,0,0,{}};}')
replace('i.status.widgets=i.frame->widgets.size();','for(const auto& w:i.frame->widgets)if(w.image&&w.image->state!="ready"){i.status.code=SurfaceCode::degraded;i.status.reason=w.image->state=="loading"?"image.pending":"image.failed";}\n            i.status.widgets=i.frame->widgets.size();')
replace('catch(const Error& e){i.histories.clear();i.frame.reset();','catch(const Error& e){i.images->clear(true);i.histories.clear();i.frame.reset();')
replace('catch(const std::bad_alloc&){i.histories.clear();i.frame.reset();','catch(const std::bad_alloc&){i.images->clear(true);i.histories.clear();i.frame.reset();')
p.write_text(t,encoding='utf-8',newline='\n')
p=r/'CMakeLists.txt';t=p.read_text().replace('source/rendering/scene_chart.cpp)','source/rendering/scene_chart.cpp source/rendering/scene_image.cpp)').replace('syspane_scene_surface PUBLIC syspane_native_text)','syspane_scene_surface PUBLIC syspane_native_text syspane_image_job)').replace('tests/scene/chart_surface_tests.cpp)','tests/scene/chart_surface_tests.cpp tests/scene/image_surface_tests.cpp)')
t=t.replace('add_test(NAME native.SCENE-CHART', 'add_test(NAME native.IMAGE-ERASURE COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/scene/native_surface.py"\n            "$<TARGET_FILE:syspane_scene_surface_tests>" "$<TARGET_FILE:syspane_text_probe>" "${CMAKE_BINARY_DIR}/native-evidence" IMAGE)\n        set_tests_properties(native.IMAGE-ERASURE PROPERTIES TIMEOUT 120)\n        add_test(NAME native.SCENE-IMAGE COMMAND syspane_scene_surface_tests "${CMAKE_SOURCE_DIR}/spec/fixtures/valid" IMAGE)\n        set_tests_properties(native.SCENE-IMAGE PROPERTIES TIMEOUT 90)\n        add_test(NAME native.SCENE-CHART')
p.write_text(t,encoding='utf-8',newline='\n')
p=r/'build-support/components.json';v=json.loads(p.read_text())
for row in v['components']:
    if row['target']=='syspane_scene_surface':row['sources'].append('source/rendering/scene_image.cpp');row['private_interfaces'].append('source/rendering/scene_image.hpp');row['allowed_dependencies'].append('syspane_image_job')
    if row['target']=='syspane_scene_surface_tests':row['sources'].append('tests/scene/image_surface_tests.cpp')
p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
