from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,zipfile
r=Path.cwd();e=r/'build-support/evidence/w-10-focus-idle-native';p=e/'binding-d46e37083044.json';z=e/'binding-d46e37083044.zip'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
with zipfile.ZipFile(z) as archive:
 raw=archive.read('selector/result.json');d=json.loads(raw);error=archive.read('selector.stderr').decode();assert d['outcome']=='fail' and 'o.get_role()' in error and 'timeout from dbind' in error
v=dict(recorded_at=datetime.now(timezone.utc).isoformat(),outcome='unresolved',record=dict(path=p.relative_to(r).as_posix(),sha256=sha(p)),archive=dict(path=z.relative_to(r).as_posix(),sha256=sha(z)),failed_child_sha256=hashlib.sha256(raw).hexdigest(),oracle_sha256=sha(r/'tests/editor/native_binding_authoring.py'),harness_sha256=sha(r/'tests/editor/native_editor.py'),observation_helper_sha256=sha(r/'tests/editor/native_observation.py'),finding='Selector mode fails during PAGE_TAB discovery when libatspi get_role raises timeout from dbind. The completed field/table/direct/persistent cases pass. The full matrix is failed; remaining cases did not execute. The exception is in captured stderr, not a fabricated error field in the child record.',limitation='The failed role query did not capture its object/address or explicit wire reply. Existing recorded UnknownObject replies occurred during separate observations and do not establish the role-timeout cause. No product/environment attribution is claimed.',next_step='Admit a bounded role/hierarchy observation investigation. Capture the exact object, owner, method and reply/lifetime around tab discovery while retaining the same selector, inputs, keyboard actions, deadlines and full expected scene/storage outcomes. Calibrate any observation-helper correction independently before rerunning dependent suites.')
(r/'out/campaign/focus-idle/remaining-failure.json').write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
v=dict(recorded_at=datetime.now(timezone.utc).isoformat(),action='build',maximum_bytes=7516192768,checkout_out_bytes=2410570554,linux_campaign_bytes=4796432074,reserved_growth_bytes=268435456,status='pass',scope='Recorded output of the preflight for the animation diagnostic. The diagnostic was launched before the coordinator polled the outstanding preflight result; this ordering mistake is preserved, not described as a correctly sequenced gate. The returned preflight passed. Later runs await their preflight completion before launch.')
(r/'out/campaign/focus-idle/animation-preflight-order.json').write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
