from pathlib import Path
r=Path.cwd();o=r/'out/campaign';s=(o/'modal_focus_probe.py').read_text()
s=s.replace('modal-focus-plan.json','modal-focus-plan-v2.json').replace('def observe(exe,exit_exe,directory):','def observe(exe,exit_exe,directory,mode):').replace("directory,'canvas'",'directory,mode')
s=s.replace("row=dict(id=id,before=snapshot(h,id));steps.append(row)","row=dict(id=id);steps.append(row)")
s=s.replace("try:original(id);row['after']=snapshot(h,id)","try:original(id);row['confirmed']=True")
s=s.replace("observe(*map(Path,sys.argv[2:5]));return","observe(*map(Path,sys.argv[2:5]),sys.argv[5]);return")
s=s.replace("'MODAL-FOCUS-DIAGNOSTIC'","'MODAL-FOCUS-MINIMAL-DIAGNOSTIC'").replace("'modal-focus-probe-'","'modal-focus-minimal-'")
s=s.replace("for n in range(3):\n            name='repetition-'+str(n+1);", "for n,mode in enumerate(PLAN['modes']*PLAN['repetitions']):\n            name='repetition-'+str(n//3+1)+'-'+mode;")
s=s.replace("str(folder/name)],env=env", "str(folder/name),mode],env=env")
(o/'modal_focus_probe_minimal.py').write_text(s,encoding='utf-8',newline='\n')
s=(o/'modal_focus_step.py').read_text().replace('modal_focus_probe.py','modal_focus_probe_minimal.py').replace('modal-focus-plan.json','modal-focus-plan-v2.json')
(o/'modal_focus_minimal_step.py').write_text(s,encoding='utf-8',newline='\n')
s=(o/'modal_focus_flow.py').read_text().replace('modal_focus_step.py','modal_focus_minimal_step.py').replace('modal-focus-execution','modal-focus-minimal-execution')
(o/'modal_focus_minimal_flow.py').write_text(s,encoding='utf-8',newline='\n')
