from pathlib import Path
import hashlib,json,subprocess,sys,jsonschema
r=Path.cwd();prefix='build-support/evidence/w-09-runtime-observation-';hp='build-support/evidence/runtime-observation-handoff.json';pending='--pending' in sys.argv
sha=lambda p:hashlib.sha256((r/p).read_bytes()).hexdigest()
def write(p,v):(r/p).write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
if not pending:
 v=json.loads((r/(prefix+'verification.json')).read_bytes());assert all(c['exit']==0 for c in v['checks'])
 unit=next(c for c in v['checks'] if 'unittest' in c['command']);assert 'Ran 60 tests' in unit['stderr'] and 'OK (skipped=2)' in unit['stderr']
 v['sealed_specification']={'path':'spec/checksums.json','sha256':sha('spec/checksums.json')};v['tool_inputs']={p:sha(p) for p in ('spec/tools/specctl.py','spec/tools/tests/test_specctl.py','tests/configuration/settings_content_fixture.py','build-support/generate_authored_schemas.py')};v['unchanged_old_contracts']={}
 for p in subprocess.check_output(['git','ls-tree','-r','--name-only','HEAD','spec/contracts','spec/fixtures'],text=True).splitlines():
  if not p.endswith('.json'):continue
  before=subprocess.check_output(['git','show','HEAD:'+p]);assert before==(r/p).read_bytes();v['unchanged_old_contracts'][p]=hashlib.sha256(before).hexdigest()
 budget=subprocess.run([str(r/'.venv/Scripts/python.exe'),'-X','utf8','build-support/check_workspace_budget.py','--action','inspect'],capture_output=True,text=True);assert budget.returncode==0;v['final_workspace_budget']=json.loads(budget.stdout);write(prefix+'verification.json',v)
files=subprocess.check_output(['git','diff','HEAD','--name-only'],text=True).splitlines()+subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();old=json.loads((r/'build-support/evidence/focus-idle-handoff.json').read_bytes())
h=dict(schema_version='0.1.0',work_id='W-09',source_ref=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),objective='Reduce complete image-validation overhead and investigate preserved native observation failures without relaxing acceptance',changed_files=sorted(set(files)|{hp,prefix+'staging.json'}),decisions=['Freeze original source and independent validation examples before the production edit.', 'Retain every dimension, length and premultiplied-channel check; avoid per-component container calls in the bounded scan.', 'Measure original/candidate work separately and retain exact pixels, flags and executables.', 'Keep historical accessibility timeouts open; six successful query trials and current matrices do not establish their cause.', 'Reserve measured rendering growth within the unchanged workspace bound and reclaim only verified committed duplicates.'],checks=[{'name':name,'outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'} for name in ('Independent validation examples pass before production change','Six affected checks per development profile','Complete non-native suites: 312 Linux, 309 Windows GCC15, 306 v141_xp','Fifteen native rendering checks plus refresh and binding matrices','Three baseline/candidate image measurements and six traced query trials')]+[{'name':'Historical binding and inspector timeout causes','outcome':'inconclusive','evidence':prefix+'attempts.json'},{'name':'Specification/tooling/integrity checks','outcome':'not_run' if pending else 'pass','evidence':prefix+'verification.json'},{'name':'Staged source/oracle/artifact/evidence identities','outcome':'not_run','evidence':prefix+'staging.json'},{'name':'Complete editions and historical/release qualification','outcome':'not_run','evidence':None}],open_questions=old['open_questions'],next_step='Continue explicit native observation evidence without inferring absence from errors; complete remaining visibility/typography, clipboard/recovery drafts and installed ownership while retaining all five edition gates.',authority_used=old['authority_used'],limitations=['Historical binding role and inspector selected-row timeouts remain unexplained.', 'The original failing paint did not record phase timings; the measured optimization removes avoidable cost and passes the unchanged current timing checks.', 'Owned Linux laboratory and contemporary Windows execution do not qualify installed desktops or historical targets.', 'Remaining authoring, native accessibility/performance, historical laboratories, other adapters and full release gates remain open.', 'Two existing Windows tooling symlink assertions remain skipped.'])
jsonschema.validate(h,json.loads((r/'spec/contracts/handoff.schema.json').read_bytes()));write(hp,h)
if pending:write(prefix+'staging.json',{'outcome':'pending'})
print('Prepared pending handoff.' if pending else 'Verified results and sealed handoff.')
