from pathlib import Path
import json,copy
r=Path.cwd()
def edit(n,a,b):
 p=r/n;s=p.read_text();assert a in s,(n,a);p.write_text(s.replace(a,b),encoding='utf-8',newline='\n')
edit('build-support/generate_authored_schemas.py',"'command-v0.7',","'command-v0.7','command-v0.8',")
edit('CMakeLists.txt','command-v0.7 command-result','command-v0.7 command-v0.8 command-result')
edit('CMakeLists.txt','source/configuration/theme_resources.cpp','source/configuration/theme_resources.cpp source/configuration/theme_command.cpp')
n='source/configuration/authored.cpp';edit(n,'command_v0_7_schema,','command_v0_7_schema,command_v0_8_schema,')
edit(n,'version=="0.7.0"?"0.7.0/command":','version=="0.8.0"?"0.8.0/command":version=="0.7.0"?"0.7.0/command":')
edit(n,'version=="0.5.0"||version=="0.6.0"||version=="0.7.0"','version=="0.5.0"||version=="0.6.0"||version=="0.7.0"||version=="0.8.0"')
edit(n,'value.value("schema_version",Json())=="0.7.0"','value.value("schema_version",Json())=="0.7.0"||value.value("schema_version",Json())=="0.8.0"')
p=r/n;s=p.read_text();begin=s.index('        const auto check=[](const Json& font)');end=s.index('        check(value.at("font"))',begin);block=s[begin:end]
function=block.replace('        const auto check=[](const Json& font){','namespace {void font_semantics(const Json& font){',1).rstrip();assert function.endswith('};');function=function[:-2]+'}}\n'
s=s[:begin]+s[end:];s=s.replace('check(value.at("font"))','font_semantics(value.at("font"))').replace('check(font);','font_semantics(font);');s=s.replace('void validate_content_document(',function+'void validate_content_document(',1);p.write_text(s,encoding='utf-8',newline='\n')
edit(n,'    (void)revision(value["expected_revision"]);','    if(version=="0.8.0"&&!value["theme_edit"].is_null()){font_semantics(value["theme_edit"]["font"]);if(!value["theme_edit"]["font_roles"].is_null())for(const auto& font:value["theme_edit"]["font_roles"])font_semantics(font);}\n    (void)revision(value["expected_revision"]);')
edit(n,'if(command.value("schema_version",Json())=="0.7.0")','if(command.value("schema_version",Json())=="0.7.0"||command.value("schema_version",Json())=="0.8.0")')
edit(n,'    if(command.contains("content"))require','    if(command.value("schema_version",Json())=="0.8.0"){\n        require(!policy.denied_capabilities.count("configuration.theme-overrides")&&!policy.denied_capabilities.count("theme.typography"),"policy.denied");\n        if(!command.at("theme_edit").is_null())require(authority.role!="saver_settings"&&!policy.denied_capabilities.count("theme.edit"),"policy.denied");\n    }\n    if(command.contains("content"))require')
for n,expr in [('source/protocol/wire.cpp','root["body"].value("schema_version",Json())'),('source/configuration/transaction.cpp','command["schema_version"]'),('source/configuration/async_commands.cpp','command["schema_version"]')]:edit(n,expr+'=="0.7.0"',expr+'=="0.7.0"||'+expr+'=="0.8.0"')
edit('source/configuration/transaction.hpp','    std::function<ResourceSnapshot(const Authored&,const Json& selection)> prepare;','    std::function<ResourceSnapshot(const Authored&,const Json& selection)> prepare;\n    std::function<void()> after_prepare{};')
edit('source/configuration/transaction.hpp','    bool supports_visibility()const','    bool supports_theme_overrides()const{return supports_visibility()&&resource_provider_.capabilities.count("scene.content")&&resource_provider_.capabilities.count("theme.typography")&&resource_provider_.capabilities.count("configuration.theme-overrides");}\n    bool supports_visibility()const')
n='source/configuration/transaction.cpp';edit(n,'#include "transaction.hpp"','#include "transaction.hpp"\n#include "theme_command.hpp"')
edit(n,'require(supports_resources(),"resource.contract");resources=resource_provider_.prepare(candidate,command["content"]);','require(supports_resources(),"resource.contract");\n            if(command["schema_version"]=="0.8.0"){require(supports_theme_overrides()&&current_.resources,"resource.contract");resources=prepare_theme_command(*current_.resources,candidate,command,checked_policy,resource_provider_.capabilities);}\n            else resources=resource_provider_.prepare(candidate,command["content"]);\n            if(resource_provider_.after_prepare)resource_provider_.after_prepare();')
edit('source/configuration/command_service.hpp','    virtual bool supports_visibility()const','    virtual bool supports_theme_overrides()const{return false;}\n    virtual bool supports_visibility()const')
edit('source/configuration/async_commands.hpp','    bool supports_visibility()const','    bool supports_theme_overrides()const override{return transactions_.supports_theme_overrides();}\n    bool supports_visibility()const')
n='source/configuration/session.cpp';edit(n,'bool visibility=false)','bool visibility=false,bool themes=false)')
edit(n,'    if (source) {','    if(themes&&visibility&&locks&&resources&&large){hello.documents.insert({"command","0.8.0"});hello.optional.insert("configuration.theme-overrides");}\n    if (source) {')
edit(n,'commands_&&commands_->supports_visibility())','commands_&&commands_->supports_visibility(),commands_&&commands_->supports_theme_overrides())')
edit(n,'c.selection.documents.count({"command", "0.7.0"})','c.selection.documents.count({"command", "0.7.0"})||c.selection.documents.count({"command", "0.8.0"})')
edit(n,'!c.selection.documents.count({"command","0.7.0"})','(!c.selection.documents.count({"command","0.7.0"})&&!c.selection.documents.count({"command","0.8.0"}))')
edit(n,'        const auto version = source_ ?','        if(!c.selection.documents.count({"command","0.8.0"})||!c.selection.features.count("configuration.visibility")){\n            if(client.required.count("configuration.theme-overrides"))throw Error("handshake.theme_overrides");\n            c.selection.features.erase("configuration.theme-overrides");\n        }\n        const auto version = source_ ?')
edit(n,'message.body.value("schema_version",Json())!="0.7.0"','message.body.value("schema_version",Json())!="0.7.0"&&message.body.value("schema_version",Json())!="0.8.0"')
edit(n,'body.value("schema_version",Json())=="0.7.0"','(body.value("schema_version",Json())=="0.7.0"||body.value("schema_version",Json())=="0.8.0")')
edit(n,'        if(commands_){\n            // Even legacy','        if(body.value("schema_version",Json())=="0.8.0"&&!c.selection.features.count("configuration.theme-overrides")){queue(c,"result",result({"invalid","feature.unsupported"},request,epoch_,revision_));return;}\n        if(commands_){\n            // Even legacy')
n='source/platform/generation_store_linux.cpp';edit(n,'#include "generation_store_linux.hpp"','#include "generation_store_linux.hpp"\n#include "theme_command.hpp"')
edit(n,'const c::Authored& documents,bool synchronize)','const c::Authored& documents,bool synchronize,bool themes)')
edit(n,'index["version"]=="0.1.0"','index["version"]==(themes?"0.2.0":"0.1.0")')
edit(n,'exact_files(dir.fd,expected);const auto resources=c::ContentCatalog(std::move(packages)).resources(index["selection"],documents);','exact_files(dir.fd,expected);const c::ContentCatalog catalog(std::move(packages));const auto resources=themes?catalog.theme_resources(index["selection"],documents):catalog.resources(index["selection"],documents);')
edit(n,'const std::function<void(const char*)>& hook){\n    need(::mkdirat(parent,"resources"','const std::function<void(const char*)>& hook,bool themes){\n    need(::mkdirat(parent,"resources"')
edit(n,'const auto index=Json{{"version","0.1.0"},{"selection"','const auto index=Json{{"version",themes?"0.2.0":"0.1.0"},{"selection"')
edit(n,'const bool separate=manifest.is_object()&&manifest.value("version",Json())=="0.3.0";','const bool themes=manifest.is_object()&&manifest.value("version",Json())=="0.4.0";\n        const bool separate=themes||(manifest.is_object()&&manifest.value("version",Json())=="0.3.0");\n        need(!themes||manifest.contains("resources"),"storage.resources");')
edit(n,'decode_resources(dir.fd,manifest["resources"],value.documents,synchronize)','decode_resources(dir.fd,manifest["resources"],value.documents,synchronize,themes)')
edit(n,'command["schema_version"]=="0.7.0")==separate','command["schema_version"]=="0.7.0"||command["schema_version"]=="0.8.0")==separate')
edit(n,'            need(command.contains("content")==resources','            need((command["schema_version"]=="0.8.0")==themes,"storage.identity_version");\n            if(themes){need(value.resources!=nullptr,"storage.resources");c::validate_theme_command_binding(command,*value.resources);}\n            need(command.contains("content")==resources')
edit(n,'            if(next.identity&&(c::parse_command(next.identity->body)', '            const bool themes=next.identity&&c::parse_command(next.identity->body)["schema_version"]=="0.8.0";\n            need(!themes||next.resources!=nullptr,"storage.resources");\n            if(next.identity&&(c::parse_command(next.identity->body)')
edit(n,'c::parse_command(next.identity->body)["schema_version"]=="0.7.0"','c::parse_command(next.identity->body)["schema_version"]=="0.7.0"||themes')
edit(n,'manifest_value["version"]="0.3.0"','manifest_value["version"]=themes?"0.4.0":"0.3.0"')
edit(n,'write_resources(dir.fd,*next.resources,hook)','write_resources(dir.fd,*next.resources,hook,themes)')
n='source/application/configuration_probe.cpp';edit(n,'const std::string fault=(argc==5','const std::string fault=(argc==5&&mode=="theme-commit")||(argc==5')
edit(n,'else if((mode=="content-commit"||mode=="visibility-commit")&&argc>=6)','else if(((mode=="content-commit"||mode=="visibility-commit")&&argc>=6)||(mode=="theme-commit"&&argc==5))')
edit(n,'if(mode=="visibility-commit")provider.capabilities.insert','if(mode=="theme-commit")provider.capabilities.insert({"scene.edit-locks","scene.visibility","theme.typography","configuration.theme-overrides"});\n        if(mode=="visibility-commit")provider.capabilities.insert')
edit(n,'if(fault=="deny-visibility")','if(fault=="deny-theme")policy.denied_capabilities.insert("configuration.theme-overrides");\n        if(fault=="deny-visibility")')
n='source/application/command_probe.cpp';edit(n,'store,{"scene.selector","scene.content"}','store,{"scene.selector","scene.content","scene.edit-locks","scene.visibility","theme.typography","configuration.theme-overrides"}')
edit(n,'resources.prepare=[prepare=std::move(resources.prepare),&prepared](const c::Authored& value,const Json& selection){auto result=prepare(value,selection);prepared();return result;};','resources.after_prepare=prepared;')
edit('spec/tools/specctl.py',"'command-v0.7'","'command-v0.7','command-v0.8'")
p=r/'build-support/components.json';v=json.loads(p.read_bytes());c=next(x for x in v['components'] if x['target']=='syspane_authored');c['sources'].append('source/configuration/theme_command.cpp');c['public_interfaces'].append('source/configuration/theme_command.hpp');p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
print('Applied versioned theme command, transaction, negotiation and native generation integration.')
