from pathlib import Path
r=Path.cwd()
def edit(name,old,new):
 p=r/name;s=p.read_text();assert old in s,name;p.write_text(s.replace(old,new,1),encoding='utf-8',newline='\n')
edit('CMakeLists.txt','tests/editor/layout_authoring_tests.cpp)','tests/editor/layout_authoring_tests.cpp tests/editor/container_tests.cpp)')
edit('CMakeLists.txt','LAYOUT-POLICY LAYOUT-GEOMETRY)','LAYOUT-POLICY LAYOUT-GEOMETRY CONTAINER-SCENES CONTAINER-GEOMETRY CONTAINER-RULES CONTAINER-ATOMIC CONTAINER-POLICY CONTAINER-COMPAT)')
edit('CMakeLists.txt','        add_test(NAME native.EDITOR-LAYOUT', '''        add_test(NAME native.EDITOR-CONTAINERS COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/editor/native_containers.py"
            "$<TARGET_FILE:syspane_editor_window>" "$<TARGET_FILE:syspane_editor_exit_probe>" "${CMAKE_BINARY_DIR}/native-evidence")
        set_tests_properties(native.EDITOR-CONTAINERS PROPERTIES TIMEOUT 600)
        add_test(NAME native.EDITOR-LAYOUT''')
edit('tests/editor/editor_draft_tests.cpp','void run_layout_authoring(', 'void run_container(const std::string&,const std::string&);\nvoid run_layout_authoring(')
edit('tests/editor/editor_draft_tests.cpp','    if(name.substr(0,7)=="LAYOUT-")','    if(name.substr(0,10)=="CONTAINER-"){run_container(name.substr(10),root);return;}\n    if(name.substr(0,7)=="LAYOUT-")')
edit('build-support/components.json','"tests/editor/layout_authoring_tests.cpp"','"tests/editor/layout_authoring_tests.cpp",\n        "tests/editor/container_tests.cpp"')
edit('tests/editor/native_editor.py','properties=False,layout=False):','properties=False,layout=False,container=False):')
edit('tests/editor/native_editor.py','sum((large,arrange,group,snap,properties,layout))','sum((large,arrange,group,snap,properties,layout,container))')
edit('tests/editor/native_editor.py','self.layout=layout;','self.container=container;self.layout=layout;')
edit('tests/editor/native_editor.py',"ROOT/('tests/editor/layout-authoring-cases.json'", "ROOT/('tests/editor/container-cases.json' if container else 'tests/editor/layout-authoring-cases.json'")
edit('tests/editor/native_editor.py','("layout-" if self.layout','("container-" if self.container else "layout-" if self.layout')
edit('tests/editor/editor_window.cpp','properties=false,layout_mode=false;', 'properties=false,layout_mode=false,container_mode=false;')
edit('tests/editor/editor_window.cpp','content=true;layout_mode=', 'content=true;container_mode=mode.substr(0,10)=="container-";layout_mode=')
edit('tests/editor/editor_window.cpp','behavior=layout_mode?', 'behavior=container_mode?mode.substr(10):layout_mode?')
edit('tests/editor/editor_window.cpp','root+(layout_mode?', 'root+(container_mode?"/tests/editor/container-cases.json":layout_mode?')
edit('tests/editor/editor_window.cpp','if(behavior=="retain-layout")', 'if(behavior=="retain-container"){canary=gtk_label_new("Retained container canary Private container");gtk_box_pack_start(GTK_BOX(box),canary,FALSE,FALSE,0);}\n        if(behavior=="retain-layout")')
edit('tests/editor/editor_window.cpp','if(behavior=="wrong-layout")','if(behavior=="wrong-container"){auto changed=c::parse_command(body);auto& children=changed["operations"][0]["scene"]["widgets"].back()["children"];std::reverse(children.begin(),children.end());body=changed.dump();}\n            if(behavior=="wrong-layout")')
edit('tests/editor/editor_window.cpp','need(layout_mode,"layout laboratory control")','need(layout_mode||container_mode,"layout laboratory control")')
for old,new in [('layout_step.py','container_step.py'),('layout_flow.py','container_flow.py')]:
 s=(r/'out/campaign'/old).read_text().replace('w-10-layout-authoring','w-10-containers').replace('layout_step.py','container_step.py').replace('layout-execution-','container-execution-')
 s=s.replace("('layout','calibration'", "('containers','layout','calibration'")
 if old.endswith('step.py'):
  s=s.replace("command={'layout':", "command={'containers':['ctest','--preset',profile,'-R','^native[.]EDITOR-CONTAINERS$','--output-on-failure'],'layout':")
  s=s.replace("artifact_name={'layout':", "artifact_name={'containers':'syspane_editor_window','layout':")
  s=s.replace("'^editor[.]LAYOUT-'", "'^editor[.]CONTAINER-'")
 (r/'out/campaign'/new).write_text(s,encoding='utf-8',newline='\n')
print('Registered portable and native container checks.')
