#include "surface_fixture.hpp"
#include <iostream>
#include <limits>
using namespace fixture;
int surface_window(const std::string&,const std::string&);
int image_surface_tests(const std::string&);
int image_surface_mock(const char*);
int chart_surface_tests(const std::string&);
int table_tests(const std::string&);
namespace {
void check_empty(v::SceneSurface& s,v::SurfaceCode code,std::uint64_t now){unsigned calls=0;s.paint(now,{},[&](auto got,const auto* f){++calls;need(got==code&&!f,"empty publication");});need(calls==1&&s.status().widgets==0&&s.status().pixels==0,"empty cache");}
void cases(const std::string& root){
    unsigned count=0;auto test=[&](const char* name,const std::function<void()>& f){f();++count;std::cout<<name<<" pass\n";};
    test("CONTENT",[&]{Owner f(root);f.attach();f.receive();auto frame=f.paint();need(frame.widgets.size()==1&&frame.widgets[0].text=="Receive\n123 byte\nCurrent","exact scalar text");need(frame.widgets[0].accessible.find("age=0 ns")!=std::string::npos,"qualified age");need(frame.layout.revision=="40"&&frame.theme_pin==f.cfg.resources->theme_pin(),"generation pins");need(frame.displays.size()==1&&frame.displays[0].width==800,"native topology");});
    test("UINT64",[&]{Owner f(root);f.attach();f.receive(document(std::numeric_limits<std::uint64_t>::max()));need(f.paint().widgets[0].text=="Receive\n18446744073709551615 byte\nCurrent","exact uint64");});
    test("ZERO-NULL",[&]{Owner f(root);f.attach();f.receive(document(0));need(f.paint().widgets[0].text=="Receive\n0 byte\nCurrent","zero is value");auto d=document(0,2);for(auto& o:d["observations"])if(o["field"]=="network.receive_bytes"){o["value"]=nullptr;o["observed_at"]=nullptr;o["measured_at"]=nullptr;o["freshness"]="unknown";o["acquisition"]="pending";}f.receive(d,3);auto text=f.paint(4).widgets[0].text;need(text=="Receive\n— byte\nFreshness unknown | Pending","null/pending exact");});
    test("FAILURE",[&]{Owner f(root);f.attach();auto d=document();for(auto& o:d["observations"])if(o["field"]=="network.receive_bytes"){o["acquisition"]="failed";o["freshness"]="stale";o["error"]={{"code","provider.failed"},{"message","private diagnostic"},{"retryable",true}};}f.receive(d);auto frame=f.paint();need(frame.widgets[0].text=="Receive\n123 byte\nStale | Source failed (provider.failed)","failure label");need(frame.widgets[0].accessible.find("private diagnostic")==std::string::npos,"error details erased");});
    test("ERASE-REGRANT",[&]{Owner f(root);f.attach();f.receive();f.paint();auto before=f.clears;f.surface->policy(policy(8,false),3);need(f.clears>before&&f.surface->status().widgets==0,"synchronous erase");check_empty(*f.surface,v::SurfaceCode::restricted,4);need(f.surface->receive("P1",f.token,7,wire(document(999),link()),5,tick()).code!=r::DataCode::accepted,"stale delivery");f.surface->policy(policy(9),6);f.revision=9;need(f.paint(7).widgets[0].text=="Receive\nWaiting","regrant no resurrection");f.attach(8);f.receive(document(456),9);need(f.paint(10).widgets[0].text=="Receive\n456 byte\nCurrent","fresh reattachment");});
    test("BOTH-CHANNELS",[&]{for(const std::string channel:{"desktop","accessibility"}){Owner f(root);f.attach();f.receive();f.paint();auto next=policy(8);next.disclosure.erase({"desktop",channel});f.surface->policy(next,3);check_empty(*f.surface,v::SurfaceCode::restricted,4);}});
    test("POLICY-ORDER",[&]{Owner f(root);f.attach();f.receive();f.paint();f.surface->policy(policy(7),3);check_empty(*f.surface,v::SurfaceCode::restricted,4);auto unavailable=policy(0);unavailable.available=false;f.surface->policy(unavailable,5);f.surface->policy(policy(6),6);check_empty(*f.surface,v::SurfaceCode::restricted,7);f.surface->policy(policy(8),8);need(f.paint(9).widgets[0].text=="Receive\nWaiting","policy high water retained");});
    test("SOURCE-LOSS",[&]{Owner f(root);f.attach();f.receive();f.paint();f.surface->disconnect("P1",f.token,7,3);need(f.paint(4).widgets[0].text=="Receive\n123 byte\nRetained","lease distinct from metric");need(f.paint(5,3000000100ULL).widgets[0].text=="Receive\n123 byte\nRetained | Stale","retained expiry");});
    test("RESTART-PIN",[&]{Owner f(root);f.attach();f.receive();f.paint();need(f.surface->attach("P1",link(7,"E2"),3).token!=0,"new epoch");auto frame=f.paint(4);need(frame.widgets[0].text.find("123")==std::string::npos,"old pin never rebinds");});
    test("UNSUPPORTED",[&]{for(const std::string kind:{"table","chart","image"}){Owner f(root);auto cfg=f.cfg;cfg.authored.scene["widgets"][0]["kind"]=kind;f.surface->replace(cfg,0);check_empty(*f.surface,v::SurfaceCode::alternative,1);need(f.surface->status().reason=="surface.unsupported","explicit capability");}});
    test("OVERFLOW",[&]{Owner f(root);auto cfg=f.cfg;cfg.topology.displays[0].work.width=10*64;f.surface->replace(cfg,0);check_empty(*f.surface,v::SurfaceCode::alternative,1);});
    test("TEXT-GROUP",[&]{Owner f(root);auto cfg=f.cfg;auto a=widget("a","text","A"),b=widget("b","text","B");b["layout"]["base"]["x"]=330;auto group=widget("g","group","Group");group["bindings"]=Json::array();group["children"]={"b","a"};group["layout"]["base"]["width"]=800;group["layout"]["base"]["height"]=600;cfg.authored.scene["roots"]={"g"};cfg.authored.scene["widgets"]={a,group,b};f.surface->replace(cfg,0);auto frame=f.paint(1);need(frame.widgets.size()==3&&frame.widgets[0].id=="g"&&frame.widgets[1].id=="b"&&frame.widgets[2].id=="a","authored preorder");need(frame.widgets[0].text.empty()&&frame.widgets[0].accessible=="Group","group semantic name");});
    test("CLEAR-FAILURE",[&]{Owner f(root);f.attach();f.receive();f.paint();f.clear_ok=false;f.surface->policy(policy(8,false),3);check_empty(*f.surface,v::SurfaceCode::closed,4);f.clear_ok=true;f.surface->policy(policy(9),5);check_empty(*f.surface,v::SurfaceCode::closed,6);});
    test("BORROW",[&]{Owner f(root);f.attach();f.receive();unsigned calls=0;bool thrown=false;try{f.surface->paint(2,{{"P1",tick()}},[&](auto,const auto*){++calls;bool blocked=false;try{f.surface->close();}catch(const std::logic_error&){blocked=true;}need(blocked,"borrow reentry");throw std::runtime_error("sink");});}catch(const std::runtime_error& e){thrown=std::string(e.what())=="sink";}need(thrown&&calls==1,"sink exception once");f.paint(3);});
    test("CLOCK-CLOSE",[&]{Owner f(root);f.attach();f.receive();f.paint(10);check_empty(*f.surface,v::SurfaceCode::closed,9);});
    test("RESOURCE-BINDING",[&]{Owner f(root);auto cfg=f.cfg;cfg.authored.scene["theme_id"]="wrong";bool invalid=false;try{f.surface->replace(cfg,0);}catch(const p::Error&){invalid=true;}need(invalid,"theme pin binding");});
    test("VISIBILITY-GATE",[&]{Owner f(root);f.attach();f.receive();f.paint();auto cfg=f.cfg;cfg.authored.scene=c::upgrade_scene_content(cfg.authored.scene);cfg.authored.scene["schema_version"]="0.5.0";
        cfg.authored.scene["widgets"][0]["visibility"]=read(root,"visibility-counter.json");std::vector<c::ContentPackage> packages;for(const auto& package:cfg.resources->packages())packages.push_back(*package);
        cfg.resources=c::ContentCatalog(std::move(packages)).resources(cfg.resources->selection(),cfg.authored);cfg.capabilities.insert({"scene.content","scene.edit-locks","scene.visibility"});
        f.surface->replace(cfg,3);check_empty(*f.surface,v::SurfaceCode::alternative,4);need(f.surface->status().reason=="surface.visibility_unavailable","authored capability does not enable conditional pixels");
        f.surface->policy(policy(8,false),5);check_empty(*f.surface,v::SurfaceCode::restricted,6);f.surface->policy(policy(9),7);check_empty(*f.surface,v::SurfaceCode::alternative,8);
        cfg.authored.settings["display"]["enabled"]=false;f.surface->replace(cfg,9);check_empty(*f.surface,v::SurfaceCode::alternative,10);need(f.surface->status().reason=="surface.visibility_unavailable","disabled display retains unsupported-version diagnosis");
        f.surface->replace(f.cfg,11);need(f.paint(12).widgets[0].text=="Receive\nWaiting","supported scene resumes without old payload");});
    test("MULTIDISPLAY-SCALE",[&]{Owner f(root);auto cfg=f.cfg;auto d=cfg.topology.displays[0];d.id="D2";d.bounds.x=d.work.x=800*64;d.pixel_x=1200;cfg.topology.displays[0].scale_numerator=3;cfg.topology.displays[0].scale_denominator=2;cfg.topology.displays.push_back(d);auto w=widget("second","text","Other display");w["display"]={{"local_id","D2"}};cfg.authored.scene["widgets"].push_back(w);cfg.authored.scene["roots"].push_back("second");f.surface->replace(cfg,0);f.attach(1);f.receive(document(),2);auto frame=f.paint(3);need(frame.displays.size()==2&&frame.displays[0].width==1200&&frame.displays[1].x==1200,"scaled displays");need(frame.layout.nodes[1].pixels.x==1200,"host pixel placement");});
    test("OVER-ALPHA",[&]{Owner f(root);auto tokens=f.cfg.resources->theme()["tokens"];tokens["background"]="#ff000080";auto cfg=config(root,{{"tokens",tokens}});auto a=widget("a","text",""),b=widget("b","text","");cfg.authored.scene["widgets"]={a,b};cfg.authored.scene["roots"]={"a","b"};f.surface->replace(cfg,0);auto frame=f.paint(1);const auto& bytes=frame.displays[0].rgba;need(bytes[0]==192&&bytes[1]==0&&bytes[2]==0&&bytes[3]==192,"premultiplied OVER");});
    test("PIXEL-LIMIT",[&]{Owner f(root);auto cfg=f.cfg;for(unsigned n=0;n<2;++n){auto d=cfg.topology.displays[0];d.id="D"+std::to_string(n+1);d.bounds=d.work={0,0,2048*64,2048*64};if(n)cfg.topology.displays.push_back(d);else cfg.topology.displays[0]=d;}f.surface->replace(cfg,0);check_empty(*f.surface,v::SurfaceCode::alternative,1);need(f.surface->status().reason=="surface.capacity","combined pixel bound");});
    test("FORCED-DISPLAY",[&]{Owner f(root);f.attach();f.receive();f.paint();auto p=policy(8);p.forced["display.enabled"]=false;f.surface->policy(p,3);check_empty(*f.surface,v::SurfaceCode::empty,4);
        auto cfg=f.cfg;cfg.authored.settings["display"]["enabled"]=false;f.surface->replace(cfg,5);p=policy(9);p.forced["display.enabled"]=true;f.surface->policy(p,6);
        need(f.paint(7).widgets[0].text=="Receive\nWaiting","mandatory enable overrides authored disable");});
    test("CLEAR-REENTRY",[&]{v::SceneSurface* pointer=nullptr;unsigned blocked=0;v::SceneSurface owner({true,"desktop",{"desktop"}},policy(),config(root),{provider()},[&]{try{pointer->status();}catch(const std::logic_error&){++blocked;}return true;});pointer=&owner;owner.paint(0,{},[](auto,const auto*){});need(blocked==1,"native clear callback reentry rejected");owner.close();});
    test("VALUE-TYPES",[&]{for(const auto kind:{m::ValueKind::boolean,m::ValueKind::number,m::ValueKind::string}){Owner f(root,kind);f.attach();auto doc=document();std::string expected;
        for(auto& o:doc["observations"])if(o["field"]=="network.receive_bytes"){o["field"]="probe.value";o["unit"]="1";
            if(kind==m::ValueKind::boolean){o["value"]={{"kind","boolean"},{"data",true}};expected="true";}
            if(kind==m::ValueKind::number){o["value"]={{"kind","number"},{"data",-0.125}};expected="-0.125";}
            if(kind==m::ValueKind::string){o["value"]={{"kind","string"},{"data","ordinary"}};expected="ordinary";}}
        f.receive(doc);need(f.paint().widgets[0].text=="Receive\n"+expected+"\nCurrent","typed formatting");}});
    std::cout<<"SURFACE-FAMILIES "<<count<<"\n";
}
}
int main(int argc,char** argv){try{if(argc<2)return 2;if(argc==3&&std::string(argv[1])=="image/png")return image_surface_mock(argv[2]);if(argc==3&&std::string(argv[2])=="IMAGE")return image_surface_tests(argv[1]);if(argc==4&&std::string(argv[2])=="WINDOW")return surface_window(argv[1],argv[3]);if(argc==3&&std::string(argv[2])=="CHART")return chart_surface_tests(argv[1]);if(argc==3&&std::string(argv[2])=="TABLE")return table_tests(argv[1]);cases(argv[1]);return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
