#include "table_fixture.hpp"
#include <algorithm>
#include <iostream>
#include <limits>
using namespace fixture;
namespace {
void reject(Owner& f,const char* reason,std::uint64_t now=2){f.surface->paint(now,{{"P1",tick()}},[&](auto code,const auto* frame){need(code==v::SurfaceCode::alternative&&!frame,"whole table alternative");});need(f.surface->status().reason==reason,"table alternative reason");}
const v::SurfaceTable& table(const v::SurfaceFrame& f){need(f.widgets.size()==1&&f.widgets[0].table.has_value(),"typed table");return *f.widgets[0].table;}
}
int table_tests(const std::string& root){unsigned count=0;auto test=[&](const char* name,const std::function<void()>& fn){fn();++count;std::cout<<name<<" pass\n";};
    test("TABLE-CONTENT",[&]{Owner f(root);table_prepare(f,root);f.receive(table_document());auto frame=f.paint();const auto& t=table(frame);
        need(t.columns==std::vector<std::string>{"network.receive_bytes","network.transmit_bytes"},"ordered headers");
        need(t.total==2&&!t.truncated&&t.rows.size()==2&&t.summary=="Showing 2 of 2 rows","complete counts");
        need(t.rows[0].entity=="network:interface:1"&&t.rows[1].entity=="network:interface:2"&&t.rows[0].producer=="P1"&&t.rows[0].epoch=="E1"&&t.rows[0].generation==1,"stable identity");
        need(t.rows[0].cells[0].text=="123 byte\nCurrent"&&t.rows[0].cells[1].text=="7 byte\nCurrent"&&t.rows[1].cells[0].text=="124 byte\nCurrent","cell content");
        need(t.rows[0].cells[0].pixels.x==0&&t.rows[0].cells[1].pixels.x>t.rows[0].cells[0].pixels.width&&t.rows[1].cells[0].pixels.y>t.rows[0].cells[0].pixels.y,"grid cells");
        need(frame.widgets[0].accessible.find("Row P1/E1/network:interface:1\nnetwork.receive_bytes: 123 byte\nCurrent\nsupport=supported;")!=std::string::npos,"accessible row scope");});
    test("TABLE-EXACT",[&]{Owner f(root);table_prepare(f,root);f.receive(table_document(std::numeric_limits<std::uint64_t>::max()));auto frame=f.paint();need(table(frame).rows[0].cells[0].text=="18446744073709551615 byte\nCurrent","exact table uint64");});
    test("TABLE-REORDER",[&]{Owner f(root);auto cfg=table_config(root);for(auto& b:cfg.authored.scene["widgets"][0]["bindings"])b["sort"]={{{"field","network.receive_bytes"},{"direction","descending"}}};f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto a=f.paint();need(table(a).rows[0].entity=="network:interface:2"&&table(a).rows[0].cells[1].text=="8 byte\nCurrent","sort entire row");f.receive(table_document(200,2),3);auto b=f.paint(4);need(table(b).rows[0].entity=="network:interface:1"&&table(b).rows[0].cells[1].text=="7 byte\nCurrent","stable key after reorder");});
    test("TABLE-MISSING-CELL",[&]{Owner f(root);table_prepare(f,root);auto d=table_document();auto& a=d["observations"];a.erase(std::remove_if(a.begin(),a.end(),[](const auto& o){return o["entity_id"]=="network:interface:1"&&o["field"]=="network.transmit_bytes";}),a.end());f.receive(d);auto frame=f.paint();need(table(frame).rows[0].cells[1].text=="Waiting"&&table(frame).rows[1].cells[1].text=="8 byte\nCurrent","missing field does not shift rows");});
    test("TABLE-TRUNCATED",[&]{Owner f(root);auto cfg=table_config(root);for(auto& b:cfg.authored.scene["widgets"][0]["bindings"])b["limit"]=1;f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto frame=f.paint();need(table(frame).truncated&&table(frame).rows.size()==1&&table(frame).total==2&&table(frame).summary=="Showing 1 of 2 rows","explicit truncation");});
    test("TABLE-EMPTY",[&]{Owner f(root);auto cfg=table_config(root);for(auto& b:cfg.authored.scene["widgets"][0]["bindings"])b["predicates"]={{{"field","entity.id"},{"op","eq"},{"value","missing"}}};f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto frame=f.paint();need(table(frame).rows.empty()&&table(frame).summary=="Showing 0 of 0 rows","empty is explicit");});
    test("TABLE-INCOMPLETE",[&]{Owner f(root);auto cfg=table_config(root);cfg.authored.scene["widgets"][0]["bindings"][1]["field"]="missing.field";f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto frame=f.paint();need(table(frame).rows.empty()&&table(frame).summary=="Unsupported field"&&frame.widgets[0].accessible.find("123")==std::string::npos,"incomplete column no partial data");});
    test("TABLE-CONTRACT",[&]{for(unsigned kind=0;kind<3;++kind){Owner f(root);auto cfg=table_config(root);auto& b=cfg.authored.scene["widgets"][0]["bindings"];if(kind==0)b[1]["limit"]=7;if(kind==1)b[1]["field"]=b[0]["field"];if(kind==2)b[0]=binding();f.surface->replace(cfg,0);reject(f,"surface.unsupported");}});
    test("TABLE-LIMIT",[&]{Owner f(root);auto cfg=table_config(root);for(auto& b:cfg.authored.scene["widgets"][0]["bindings"])b["limit"]=65;f.surface->replace(cfg,0);reject(f,"surface.capacity");});
    test("TABLE-NULL-ZERO",[&]{Owner f(root);table_prepare(f,root);auto d=table_document(0);for(auto& o:d["observations"])if(o["field"]=="network.transmit_bytes"&&o["entity_id"]=="network:interface:1"){o["value"]=nullptr;o["observed_at"]=nullptr;o["measured_at"]=nullptr;o["freshness"]="unknown";o["acquisition"]="pending";}f.receive(d);auto frame=f.paint();need(table(frame).rows[0].cells[0].text=="0 byte\nCurrent"&&table(frame).rows[0].cells[1].text=="— byte\nFreshness unknown | Pending","zero/null table semantics");});
    test("TABLE-RETAINED",[&]{Owner f(root);table_prepare(f,root);f.receive(table_document());f.surface->disconnect("P1",f.token,7,2);auto frame=f.paint(3,3000000100ULL);need(table(frame).rows[0].cells[0].text=="123 byte\nRetained | Stale","retained table age");});
    test("TABLE-POLICY",[&]{Owner f(root);table_prepare(f,root);f.receive(table_document());f.paint();f.surface->policy(policy(8,false),3);f.surface->paint(4,{},[&](auto code,const auto* frame){need(code==v::SurfaceCode::restricted&&!frame,"table erasure");});f.surface->policy(policy(9),5);auto frame=f.paint(6);need(table(frame).rows.empty()&&table(frame).summary=="Waiting"&&frame.widgets[0].accessible.find("123")==std::string::npos,"table regrant empty");});
    test("TABLE-BACKGROUND",[&]{for(const std::string contrast:{"authored","light","dark"}){Owner f(root);auto tokens=f.cfg.resources->theme()["tokens"];tokens["background"]="#ff000080";auto cfg=table_config(root,{{"tokens",tokens}});cfg.contrast=contrast;f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto frame=f.paint();const auto& t=table(frame);const auto& cell=t.rows[0].cells[1];const auto offset=(static_cast<std::size_t>(cell.pixels.y)*800+cell.pixels.x-2)*4;const auto& p=frame.displays[0].rgba;
        if(contrast=="authored")need(p[offset]==128&&p[offset+1]==0&&p[offset+3]==128,"table background blended once");else need(p[offset]==(contrast=="light"?255:0)&&p[offset+3]==255,"table contrast background");}});
    test("TABLE-COLUMN-BOUND",[&]{Owner f(root);auto cfg=table_config(root);auto& b=cfg.authored.scene["widgets"][0]["bindings"];b=Json::array();for(unsigned i=0;i<17;++i)b.push_back(collection("field"+std::to_string(i)));f.surface->replace(cfg,0);reject(f,"surface.capacity");});
    test("TABLE-CELL-BOUND",[&]{Owner f(root);auto cfg=table_config(root);auto& b=cfg.authored.scene["widgets"][0]["bindings"];b=Json::array();for(const std::string field:{"entity.id","entity.kind","entity.display_name","network.receive_bytes","network.transmit_bytes"})b.push_back(collection(field,64));f.surface->replace(cfg,0);f.attach();
        syspane::platform::NetworkResult rows{syspane::platform::NetworkCode::success};for(unsigned i=1;i<=53;++i)rows.rows.push_back({i,i,6,syspane::platform::NetworkCounters{1,2}});n::NetworkState state("E1","clock:1","scope:1");state.demand(1);need(state.commit(1,0,rows,tick(),tick())==n::NetworkStateCode::accepted,"large fixture");f.receive(n::network_document(*state.sample(),1,"2026-10-06T00:00:00Z","2026-10-06T00:00:01Z",true));reject(f,"surface.capacity");});
    test("TABLE-SCALE",[&]{Owner f(root);auto cfg=table_config(root);cfg.topology.displays[0].scale_numerator=3;cfg.topology.displays[0].scale_denominator=2;f.surface->replace(cfg,0);f.attach();f.receive(table_document());auto frame=f.paint();const auto& t=table(frame);v::TextRequest q;q.theme=cfg.resources->theme();q.text="network.receive_bytes";q.numerator=3;q.denominator=2;auto header=v::render_text(q);auto width=header.width;for(const auto& row:t.rows)width=std::max(width,static_cast<unsigned>(row.cells[0].pixels.width));need(t.rows[0].cells[1].pixels.x==width+12,"scaled column gap");});
    std::cout<<"TABLE-FAMILIES "<<count<<"\n";return 0;
}
