from pathlib import Path
import hashlib,json,subprocess,sys,jsonschema
r=Path.cwd();prefix='build-support/evidence/w-10-layout-authoring-';hp='build-support/evidence/layout-authoring-handoff.json';pending='--pending' in sys.argv
sha=lambda p:hashlib.sha256((r/p).read_bytes()).hexdigest()
def write(p,v):(r/p).write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
if not pending:
 v=json.loads((r/(prefix+'verification.json')).read_bytes());assert all(c['exit']==0 for c in v['checks'])
 unit=next(c for c in v['checks'] if 'unittest' in c['command']);assert 'Ran 60 tests' in unit['stderr'] and 'OK (skipped=2)' in unit['stderr'];assert json.loads(next(c for c in v['checks'] if '--schemas' in c['command'])['stdout'])['status']=='pass'
 v['sealed_specification']={'path':'spec/checksums.json','sha256':sha('spec/checksums.json')};v['tool_inputs']={p:sha(p) for p in ('spec/tools/specctl.py','spec/tools/tests/test_specctl.py','tests/configuration/settings_content_fixture.py')};v['unchanged_old_contracts']={}
 for p in subprocess.check_output(['git','ls-tree','-r','--name-only','HEAD','spec/contracts','spec/fixtures'],text=True).splitlines():
  if not p.endswith('.json') or p=='spec/fixtures/catalog.json':continue
  before=subprocess.check_output(['git','show','HEAD:'+p]);assert before==(r/p).read_bytes();v['unchanged_old_contracts'][p]=hashlib.sha256(before).hexdigest()
 budget=subprocess.run([str(r/'.venv/Scripts/python.exe'),'-X','utf8','build-support/check_workspace_budget.py','--action','inspect'],capture_output=True,text=True);assert budget.returncode==0;v['final_workspace_budget']=json.loads(budget.stdout);write(prefix+'verification.json',v)
 index=json.loads((r/(prefix+'attempts.json')).read_bytes());assert all(len(x['cases'])==132 for x in index['final_runs'].values());assert sum(x['cases'] for x in index['final_native'].values())==157
files=subprocess.check_output(['git','diff','HEAD','--name-only'],text=True).splitlines()+subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();h=json.loads((r/'build-support/evidence/content-properties-handoff.json').read_bytes())
h.update(source_ref=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),objective='Add native layout and active fixed variants through existing atomic draft, resource, policy and persistence owners',changed_files=sorted(set(files)|{hp,prefix+'staging.json'}),
 decisions=['Freeze complete authored/expected scenes, exact geometry, package and resource/schema inputs before implementation.', 'Keep existing layout kinds/versions, ordered breakpoints, whole-root display intent and explicit active fixed-variant operations.', 'Use private per-kind/variant buffers, one atomic Set layout history entry and separate durable Apply.', 'Preserve original compile/test/native failures with exact source identities.', 'Keep the 7 GiB workspace limit and all five release tracks.'],
 checks=[{'name':'132 affected checks on each of three toolchains','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'157 native cases across ten matrices','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'Schema, fixture, tooling and integrity checks','outcome':'not_run' if pending else 'pass','evidence':prefix+'verification.json'}, {'name':'Staged source/oracle/artifact/evidence identities','outcome':'not_run','evidence':prefix+'staging.json'}, {'name':'Complete native editions and historical/release qualification','outcome':'not_run','evidence':None}],
 next_step='Investigate preserved native focus/interface failures. Close flow/container group transformations and remaining properties, then installed controller/catalog/policy ownership, scene-aligned entry/restoration and independent escape. Continue all five release tracks.',
 limitations=['Owned Linux ext4/Xvfb/DBus evidence does not qualify installed editing or physical power-loss durability.', 'Provider discovery, flow/container group transformations, lock/visibility/typography, clipboard authority and recovery drafts remain required.', 'Full accessibility/performance, other adapters, historical laboratories and every complete-edition gate remain open.', 'Windows builds run on contemporary Windows; two existing symlink tooling assertions remain skipped.', 'AT-SPI button-focus failure after modal closure is preserved with X11 ownership and state; pointer-driven layout buttons do not qualify all keyboard/accessibility paths. Earlier intermittent failures also remain unresolved.'])
jsonschema.validate(h,json.loads((r/'spec/contracts/handoff.schema.json').read_bytes()));write(hp,h)
if pending:write(prefix+'staging.json',{'outcome':'pending'})
print('Prepared pending handoff.' if pending else 'Verified results and sealed handoff.')
