from pathlib import Path
import subprocess
r=Path.cwd();o=r/'out/campaign';base=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()
def save(name,s):(o/name).write_text(s,encoding='utf-8',newline='\n')
def common(s):return s.replace('w-10-widget-creation','w-10-layout-authoring').replace('widget-creation-handoff','layout-authoring-handoff').replace('8ecf403ebef7622c967f10b90d337d6c3d7037de',base).replace('124','132').replace('129','157').replace('creation-execution','layout-execution').replace('creation-staging','layout-staging')
s=(o/'archive_observation.py').read_text().replace('w-10-native-observation','w-10-layout-authoring').replace("('NATIVE-OBSERVATION',", "('EDITOR-LAYOUT','NATIVE-OBSERVATION',")
save('archive_layout.py',s)
s=common((o/'preserve_creation.py').read_text())
a=s.index('helpers=');b=s.index('\nfor p in [',a)
s=s[:a]+"helpers=['prune_layout_duplicates.py','layout-pruned-duplicates.json','prepare_layout_authoring.py','integrate_layout_authoring.py','setup_layout_native.py','setup_layout_execution.py','layout_step.py','layout_flow.py','document_layout.py','archive_layout.py','preserve_layout.py','setup_layout_evidence.py','finish_layout_checks.py','finish_layout.py','stage_layout.py']"+s[b:]
s=s.replace("for action in ('creation',", "for action in ('layout','calibration','creation',")
s=s.replace("families={'EDITOR-WIDGET-CREATION'", "families={'EDITOR-LAYOUT':('syspane_editor_window','tests/editor/native_layout_authoring.py',21),'EDITOR-OBSERVATION':('syspane_editor_window','tests/editor/native_observation_cases.py',7),'EDITOR-WIDGET-CREATION'")
s=s.replace("    if family=='EDITOR-WIDGET-CREATION':", "    if family=='EDITOR-LAYOUT':assert v['fixture_sha256']==sha(r/'tests/editor/layout-authoring-cases.json') and v['harness_sha256']==sha(r/'tests/editor/native_editor.py')\n    if family=='EDITOR-WIDGET-CREATION':")
s=s.replace("validation_attempts=[dict(record=ref(history/'creation-verification-first.json'),document=ref(history/'layout-authoring-handoff-before-links.md'))]", "validation_attempts=[]")
s=s.replace('independent native creation, binding, content, snap, group, arrange, editor and large-command/store/IPC cases', 'independent native layout, observation calibration, creation, binding, content, snap, group, arrange, editor and large-command/store/IPC cases')
save('preserve_layout.py',s)
save('finish_layout_checks.py',common((o/'finish_creation_checks.py').read_text()))
s=common((o/'finish_creation.py').read_text()).replace('native creation of all seven primitives', 'native layout and active fixed variants').replace('157 native cases across eight matrices','157 native cases across ten matrices')
s=s.replace('Freeze exact default objects, full expected scenes and resource inputs before implementation.', 'Freeze complete authored/expected scenes, exact geometry, package and resource/schema inputs before implementation.')
s=s.replace('Keep parent-local geometry and root/group display intent explicit; images require an admitted choice.', 'Keep existing layout kinds/versions, ordered breakpoints, whole-root display intent and explicit active fixed-variant operations.')
s=s.replace('Use separate private buffers, atomic insertion/selection history and separate durable Apply.', 'Use private per-kind/variant buffers, one atomic Set layout history entry and separate durable Apply.')
s=s.replace('responsive/flow transforms', 'flow/container group transformations')
s=s.replace('Intermittent AT-SPI interface and keyboard-focus failures are preserved; unchanged reruns do not establish their cause or complete native qualification.', 'AT-SPI button-focus failure after modal closure is preserved with X11 ownership and state; pointer-driven layout buttons do not qualify all keyboard/accessibility paths. Earlier intermittent failures also remain unresolved.')
save('finish_layout.py',s)
s=common((o/'stage_creation.py').read_text())
s=s.replace("    if family=='EDITOR-WIDGET-CREATION':", "    if family=='EDITOR-LAYOUT':check('tests/editor/layout-authoring-cases.json',report['fixture_sha256'])\n    if family=='EDITOR-WIDGET-CREATION':")
s=s.replace("if family in ('EDITOR-WIDGET-CREATION'", "if family in ('EDITOR-LAYOUT','EDITOR-WIDGET-CREATION'")
s=s.replace("check('tests/editor/widget-creation-cases.json' if family", "check('tests/editor/layout-authoring-cases.json' if family=='EDITOR-LAYOUT' else 'tests/editor/widget-creation-cases.json' if family")
s=s.replace("check('tests/editor/native_widget_creation.py' if family", "check('tests/editor/native_layout_authoring.py' if family=='EDITOR-LAYOUT' else 'tests/editor/native_widget_creation.py' if family")
s=s.replace("('wrong-insert','retain-create'", "('wrong-layout','retain-layout','wrong-insert','retain-create'")
s=s.replace('Staged shared and native widget creation', 'Staged shared and native layout authoring')
save('stage_layout.py',s)
