from pathlib import Path
import json,subprocess,jsonschema
r=Path.cwd();e=r/'build-support/evidence';prefix='w-10-theme-overrides-';hp=e/'theme-overrides-handoff.json';sp=e/(prefix+'staging.json')
def write(p,v):p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
if not sp.exists():write(sp,dict(outcome='not_run'))
index=json.loads((e/(prefix+'attempts.json')).read_bytes());verification=json.loads((e/(prefix+'verification.json')).read_bytes());assert all(c['exit']==0 for c in verification['checks'])
def check(name,suffix,outcome='pass'):return dict(name=name,outcome=outcome,evidence='build-support/evidence/'+prefix+suffix+'.json' if suffix else None)
h=dict(schema_version='0.1.0',work_id='W-10',source_ref=index['source_base'],objective='Implement bounded versioned immutable theme resource selection and replacement for durable font authoring.',changed_files=[],decisions=['Keep the original preset/image closure and at most one external canonical authored theme.','Separate explicit new selection resolution from legacy command/store consumers.','Validate all artifact fields and bytes; reject collisions and capacity exhaustion atomically.','Preserve fixed expectations and existing product limits.','Keep negotiated command/store integration, atomic editor history and native controls required.'],checks=[check('Resolution/replacement/invalid/capacity families and frozen closure expectations','attempts'),check('Full portable suites: 347 Linux, 344 Windows GCC15, 341 v141_xp','attempts'),check('Legacy native generation/content-command regressions','native-index'),check('Specification, fixtures, tooling and integrity','verification'),check('Staged source/oracle/artifact identity','staging','not_run'),check('New-version durable command/store integration',None,'not_run'),check('Native theme controls and trusted editor admission',None,'not_run'),check('Five complete editions and release qualification',None,'not_run')],open_questions=['Historical target floors and Mac laboratories remain unresolved.','Historical accessibility timeout causes remain unexplained.'],next_step='Close negotiated authored theme command and versioned generation/resource publication with interruption, exact replay and restart/reconciliation. Then connect atomic editor resource history and native font controls with independent preview/save/reopen/erasure evidence.',authority_used=['user:foundation-native-campaign-2026-10-05','User-expanded complete SysPane 0.1.0 release objective','User instruction to commit and sync main'],limitations=['Explicit component API does not save edited themes or admit them through old command/storage formats.','Native regressions cover existing formats only.','Historical toolset execution on contemporary Windows does not qualify XP.','Two existing Windows symlink tooling assertions remain skipped.','Installed ownership, full editions and release qualification remain open.'])
paths=set(subprocess.check_output(['git','diff','HEAD','--name-only'],text=True).splitlines())|set(subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines())|{'build-support/evidence/theme-overrides-handoff.json'}
h['changed_files']=sorted(paths);jsonschema.validate(h,json.loads((r/'spec/contracts/handoff.schema.json').read_bytes()));write(hp,h);print('Prepared handoff for',len(paths),'files.')
