from pathlib import Path
import hashlib,json,subprocess,sys,jsonschema
r=Path.cwd();prefix='build-support/evidence/w-10-edit-locks-';hp='build-support/evidence/edit-locks-handoff.json';pending='--pending' in sys.argv
sha=lambda p:hashlib.sha256((r/p).read_bytes()).hexdigest()
def write(p,v):(r/p).write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
if not pending:
 v=json.loads((r/(prefix+'verification.json')).read_bytes());assert all(c['exit']==0 for c in v['checks'])
 unit=next(c for c in v['checks'] if 'unittest' in c['command']);assert 'Ran 60 tests' in unit['stderr'] and 'OK (skipped=2)' in unit['stderr'];assert json.loads(next(c for c in v['checks'] if '--schemas' in c['command'])['stdout'])['status']=='pass'
 v['sealed_specification']={'path':'spec/checksums.json','sha256':sha('spec/checksums.json')};v['tool_inputs']={p:sha(p) for p in ('spec/tools/specctl.py','spec/tools/tests/test_specctl.py','tests/configuration/settings_content_fixture.py','build-support/generate_authored_schemas.py')};v['unchanged_old_contracts']={}
 for p in subprocess.check_output(['git','ls-tree','-r','--name-only','HEAD','spec/contracts','spec/fixtures'],text=True).splitlines():
  if not p.endswith('.json') or p=='spec/fixtures/catalog.json':continue
  before=subprocess.check_output(['git','show','HEAD:'+p]);assert before==(r/p).read_bytes();v['unchanged_old_contracts'][p]=hashlib.sha256(before).hexdigest()
 budget=subprocess.run([str(r/'.venv/Scripts/python.exe'),'-X','utf8','build-support/check_workspace_budget.py','--action','inspect'],capture_output=True,text=True);assert budget.returncode==0;v['final_workspace_budget']=json.loads(budget.stdout);write(prefix+'verification.json',v)
 index=json.loads((r/(prefix+'attempts.json')).read_bytes());assert all(len(x['cases'])==146 for x in index['final_runs'].values());assert sum(x['cases'] for x in index['final_native'].values())==156 and index['regressions']['large']['outcome']=='fail'
files=subprocess.check_output(['git','diff','HEAD','--name-only'],text=True).splitlines()+subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();h=json.loads((r/'build-support/evidence/content-properties-handoff.json').read_bytes())
h.update(source_ref=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),objective='Implement persistent own/inherited editor locks with negotiated scenes, native guards and durable recovery',changed_files=sorted(set(files)|{hp,prefix+'staging.json'}),
 decisions=['Freeze package, new schemas and full expected scenes before implementation; retain all old schemas.', 'Keep edit guards distinct from policy and live layout; explicit unlock and history remain available.', 'Require scene/content/edit-lock and command 0.6 negotiation through existing resource and transaction owners.', 'Preserve initial build/schema failures and numeric-label oracle correction without changing frozen expectations.', 'Retain the fixed workspace bound and all five release tracks.'],
 checks=[{'name':'146 affected checks on each of three toolchains','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'All non-native CTest suites on three toolchains','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'180 native cases across twelve matrices','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'Schema, fixture, tooling and integrity checks','outcome':'not_run' if pending else 'pass','evidence':prefix+'verification.json'}, {'name':'Staged source/oracle/artifact/evidence identities','outcome':'not_run','evidence':prefix+'staging.json'}, {'name':'Complete native editions and historical/release qualification','outcome':'not_run','evidence':None}],
 next_step='Continue conditional visibility, typography, clipboard authority, recovery drafts and installed controller/catalog/policy ownership; retain all five complete-edition gates.',
 limitations=['Owned Linux ext4/Xvfb/DBus evidence does not qualify installed editing, historical platforms or physical power-loss durability.', 'Locks guard ordinary editor operations, not authorization, disclosure or dynamic layout.', 'Conditional visibility, typography, clipboard/recovery drafts, installed ownership and complete accessibility/performance remain required.', 'Windows builds run on contemporary Windows; two existing tooling symlink assertions remain skipped.', 'Earlier unrelated focus/interface causes and historical laboratory/release gates remain open.'])
native_check=next(c for c in h['checks'] if c['name']=='180 native cases across twelve matrices');native_check['name']='Complete 180-case native regression set';native_check['outcome']='fail';native_check['evidence']=prefix+'focus.json'
h['checks'].append({'name':'156 native cases across eleven passing matrices','outcome':'pass','evidence':prefix+'attempts.json'})
h['checks'].append({'name':'Intermittent native Apply/Undo focus reliability','outcome':'fail','evidence':prefix+'focus.json'})
h['limitations'].append('The large-command matrix failed both attempts: Apply focus first, Undo focus on rerun. One of three direct reproductions also failed; six subsequent diagnostic passes do not repair this unresolved failure. This checkpoint is not qualified.')
h['next_step']='Investigate the reproduced large-scene Apply/Undo focus failures; then continue conditional visibility, typography, clipboard authority, recovery drafts and installed ownership, retaining all five complete-edition gates.'
jsonschema.validate(h,json.loads((r/'spec/contracts/handoff.schema.json').read_bytes()));write(hp,h)
if pending:write(prefix+'staging.json',{'outcome':'pending'})
print('Prepared pending handoff.' if pending else 'Verified results and sealed handoff.')
