from pathlib import Path
import json
r=Path.cwd()
def edit(n,a,b):
 p=r/n;s=p.read_text();assert a in s,(n,a);p.write_text(s.replace(a,b),encoding='utf-8',newline='\n')
edit('CMakeLists.txt','scene-v0.2 scene-v0.3 layout','scene-v0.2 scene-v0.3 scene-v0.4 layout')
edit('CMakeLists.txt','command-v0.4 command-v0.5 command-result','command-v0.4 command-v0.5 command-v0.6 command-result')
edit('source/configuration/authored.cpp','scene_v0_2_schema,scene_v0_3_schema,','scene_v0_2_schema,scene_v0_3_schema,scene_v0_4_schema,')
edit('source/configuration/authored.cpp','command_v0_5_schema,','command_v0_5_schema,command_v0_6_schema,')
edit('source/configuration/authored.cpp','if(scene["schema_version"]=="0.3.0")content_semantics','if(scene["schema_version"]!="0.2.0")content_semantics')
edit('source/configuration/authored.cpp','structural(value,value.is_object()&&value.contains("schema_version")&&value["schema_version"]=="0.3.0"?"0.3.0/scene":"0.2.0/scene",262144);','const auto version=value.is_object()?value.value("schema_version",Json()):Json();structural(value,version=="0.4.0"?"0.4.0/scene":version=="0.3.0"?"0.3.0/scene":"0.2.0/scene",262144);')
edit('source/configuration/authored.cpp','if(value["schema_version"]=="0.3.0")return value;','if(value["schema_version"]!="0.2.0")return value;')
edit('source/configuration/authored.cpp','value.value("schema_version",Json())=="0.5.0"','(value.value("schema_version",Json())=="0.5.0"||value.value("schema_version",Json())=="0.6.0")')
edit('source/configuration/authored.cpp','structural(value,version=="0.5.0"?','structural(value,version=="0.6.0"?"0.6.0/command":version=="0.5.0"?')
edit('source/configuration/authored.cpp','version=="0.5.0"?protocol::','(version=="0.5.0"||version=="0.6.0")?protocol::')
edit('source/configuration/authored.cpp','if(version=="0.5.0")validate_scene_document','if(version=="0.5.0"||version=="0.6.0")validate_scene_document')
for n in ('source/configuration/transaction.cpp','source/configuration/async_commands.cpp'):
 edit(n,'command["schema_version"]=="0.5.0"','(command["schema_version"]=="0.5.0"||command["schema_version"]=="0.6.0")')
edit('source/protocol/wire.cpp','root["body"].value("schema_version",Json())=="0.5.0"','(root["body"].value("schema_version",Json())=="0.5.0"||root["body"].value("schema_version",Json())=="0.6.0")')
edit('source/configuration/content.cpp','if(candidate.scene["schema_version"]=="0.3.0")','if(candidate.scene["schema_version"]!="0.2.0")')
edit('source/configuration/content.cpp','if(candidate.scene["schema_version"]!="0.3.0")return;','if(candidate.scene["schema_version"]=="0.2.0")return;')
edit('source/configuration/content.cpp','result->required_.insert("scene.content");','result->required_.insert("scene.content");\n    if(candidate.scene["schema_version"]=="0.4.0")result->required_.insert("scene.edit-locks");')
edit('source/configuration/content.cpp','scene["schema_version"]=="0.3.0"){result.command','scene["schema_version"]!="0.2.0"){result.command')
edit('source/configuration/content.cpp','result.command["content"]={{"package",package_pin},{"preset",selected}};}','result.command["content"]={{"package",package_pin},{"preset",selected}};}\n    if(scene["schema_version"]=="0.4.0"){need(capabilities.count("configuration.edit-locks")&&capabilities.count("configuration.large-commands"),"resource.capability");result.command["schema_version"]="0.6.0";}')
for subject in ('value.documents','next.documents'):
 edit('source/platform/generation_store_linux.cpp',subject+'.scene["schema_version"]!="0.3.0"',subject+'.scene["schema_version"]=="0.2.0"')
for n in ('source/interfaces/editor_draft.cpp','source/interfaces/editor_create.cpp','source/interfaces/editor_create_form_linux.cpp','source/interfaces/editor_content_form_linux.cpp','source/interfaces/editor_form_linux.cpp'):
 edit(n,'=="0.3.0"','!="0.2.0"')
edit('source/interfaces/settings_draft.cpp','scene_changed&&draft_->scene["schema_version"]=="0.3.0"','scene_changed&&draft_->scene["schema_version"]!="0.2.0"')
edit('source/interfaces/settings_draft.cpp','if(context_)result["content"]=context_->selection;','if(context_)result["content"]=context_->selection;\n    if(scene_changed&&draft_->scene["schema_version"]=="0.4.0"){need(large_commands_&&context_&&context_->capabilities.count("configuration.edit-locks"),"settings.edit_locks");result["schema_version"]="0.6.0";}')
edit('source/interfaces/settings_draft.cpp','value.scene["schema_version"]=="0.2.0"','value.scene["schema_version"]=="0.2.0"')
edit('source/configuration/command_service.hpp','virtual bool supports_large_commands()const{return false;}','virtual bool supports_large_commands()const{return false;}\n    virtual bool supports_edit_locks()const{return false;}')
edit('source/configuration/transaction.hpp','bool supports_resources()const{return static_cast<bool>(resource_provider_.prepare);}','bool supports_resources()const{return static_cast<bool>(resource_provider_.prepare);}\n    bool supports_edit_locks()const{return supports_resources()&&resource_provider_.capabilities.count("scene.edit-locks");}')
edit('source/configuration/async_commands.hpp','bool supports_large_commands()const override{return true;}','bool supports_large_commands()const override{return true;}\n    bool supports_edit_locks()const override{return transactions_.supports_edit_locks();}')
edit('source/configuration/session.cpp','bool large=false) {','bool large=false,bool locks=false) {')
edit('source/configuration/session.cpp','if (source) {','if(locks&&resources&&large){hello.documents.insert({"command","0.6.0"});hello.optional.insert("configuration.edit-locks");}\n    if (source) {')
edit('source/configuration/session.cpp','commands_&&commands_->supports_large_commands()), client','commands_&&commands_->supports_large_commands(),commands_&&commands_->supports_edit_locks()), client')
edit('source/configuration/session.cpp','c.selection.documents.count({"command", "0.5.0"}))','c.selection.documents.count({"command", "0.5.0"})||c.selection.documents.count({"command", "0.6.0"}))')
edit('source/configuration/session.cpp','!c.selection.documents.count({"command","0.5.0"})','(!c.selection.documents.count({"command","0.5.0"})&&!c.selection.documents.count({"command","0.6.0"}))')
edit('source/configuration/session.cpp','const auto version = source_ ? source_->document_version : "0.1.0";','if(!c.selection.documents.count({"command","0.6.0"})||!c.selection.features.count("configuration.large-commands")||!c.selection.features.count("configuration.content")||!c.selection.features.count("configuration.scene-content")){\n            if(client.required.count("configuration.edit-locks"))throw Error("handshake.edit_locks");\n            c.selection.features.erase("configuration.edit-locks");\n        }\n        const auto version = source_ ? source_->document_version : "0.1.0";')
edit('source/configuration/session.cpp','message.body.value("schema_version",Json())!="0.5.0"','message.body.value("schema_version",Json())!="0.5.0"&&message.body.value("schema_version",Json())!="0.6.0"')
edit('source/configuration/session.cpp','if(body.value("schema_version",Json())=="0.5.0"){','if(body.value("schema_version",Json())=="0.6.0"&&!c.selection.features.count("configuration.edit-locks")){queue(c,"result",result({"invalid","feature.unsupported"},request,epoch_,revision_));return;}\n        if(body.value("schema_version",Json())=="0.5.0"||body.value("schema_version",Json())=="0.6.0"){')
edit('source/configuration/session.cpp','op["scene"].value("schema_version",Json())=="0.3.0"','(op["scene"].value("schema_version",Json())=="0.3.0"||op["scene"].value("schema_version",Json())=="0.4.0")')
edit('spec/tools/specctl.py',"'command-v0.4','command-v0.5'","'command-v0.4','command-v0.5','command-v0.6'")
edit('spec/tools/specctl.py',"'scene-v0.2','scene-v0.3'","'scene-v0.2','scene-v0.3','scene-v0.4'")
edit('spec/tools/specctl.py',"schema_name == 'scene-v0.3'","schema_name in ('scene-v0.3','scene-v0.4')")
p=r/'spec/fixtures/catalog.json';v=json.loads(p.read_bytes())
for name,schema,valid in [('scene-edit-locks','scene-v0.4',True),('command-edit-locks','command-v0.6',True),('scene-edit-lock-type','scene-v0.4',False),('scene-old-edit-lock','scene-v0.3',False),('command-old-edit-lock','command-v0.5',False)]:
 v['fixtures'].append(dict(path='fixtures/'+('valid' if valid else 'invalid')+'/'+name+'.json',schema=schema,expected='valid' if valid else 'invalid',semantic=valid,reason='Persistent edit-lock version, type and compatibility boundary.'))
p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
