from pathlib import Path
import hashlib,json,subprocess,sys,jsonschema
r=Path.cwd();prefix='build-support/evidence/w-10-binding-authoring-';hp='build-support/evidence/binding-authoring-handoff.json';pending='--pending' in sys.argv
sha=lambda p:hashlib.sha256((r/p).read_bytes()).hexdigest()
def write(p,v):(r/p).write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8',newline='\n')
if not pending:
 v=json.loads((r/(prefix+'verification.json')).read_bytes());assert all(c['exit']==0 for c in v['checks'])
 unit=next(c for c in v['checks'] if 'unittest' in c['command']);assert 'Ran 60 tests' in unit['stderr'] and 'OK (skipped=2)' in unit['stderr'];assert json.loads(next(c for c in v['checks'] if '--schemas' in c['command'])['stdout'])['status']=='pass'
 v['sealed_specification']={'path':'spec/checksums.json','sha256':sha('spec/checksums.json')};v['tool_inputs']={p:sha(p) for p in ('spec/tools/specctl.py','spec/tools/tests/test_specctl.py','tests/configuration/settings_content_fixture.py')};v['unchanged_old_contracts']={}
 for p in subprocess.check_output(['git','ls-tree','-r','--name-only','HEAD','spec/contracts','spec/fixtures'],text=True).splitlines():
  if not p.endswith('.json') or p=='spec/fixtures/catalog.json':continue
  before=subprocess.check_output(['git','show','HEAD:'+p]);assert before==(r/p).read_bytes();v['unchanged_old_contracts'][p]=hashlib.sha256(before).hexdigest()
 budget=subprocess.run([str(r/'.venv/Scripts/python.exe'),'-X','utf8','build-support/check_workspace_budget.py','--action','inspect'],capture_output=True,text=True);assert budget.returncode==0;v['final_workspace_budget']=json.loads(budget.stdout);write(prefix+'verification.json',v)
 index=json.loads((r/(prefix+'attempts.json')).read_bytes());assert all(len(x['cases'])==118 for x in index['final_runs'].values());assert sum(x['cases'] for x in index['final_native'].values())==130
files=subprocess.check_output(['git','diff','HEAD','--name-only'],text=True).splitlines()+subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();h=json.loads((r/'build-support/evidence/content-properties-handoff.json').read_bytes())
h.update(source_ref=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),objective='Add exact native binding authoring through existing atomic draft, resolver, policy and persistence owners',changed_files=sorted(set(files)|{hp,prefix+'staging.json'}),
 decisions=['Freeze exact descriptors/scenes and resource inputs before implementation; freeze supplemental text cases before closing the native control-character boundary.', 'Keep widget mode and table query/column coupling explicit; do not grant mapping or discovery authority.', 'Preserve exact integer predicates and decoded text; serialize only active binding members.', 'Use bounded modal input, one atomic Set, separate durable Apply and immediate erasure on owner/policy change.', 'Preserve original compile, ownership-manifest, lifecycle-test and native observer failures with exact source identities.', 'Retain the 7 GiB workspace limit and remove only verified duplicate outputs of committed archives.'],
 checks=[{'name':'118 affected checks on each of three toolchains','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'130 native cases across eight matrices','outcome':'not_run' if pending else 'pass','evidence':prefix+'attempts.json'}, {'name':'Schema, fixture, tooling and integrity checks','outcome':'not_run' if pending else 'pass','evidence':prefix+'verification.json'}, {'name':'Staged source/oracle/artifact/evidence identities','outcome':'not_run','evidence':prefix+'staging.json'}, {'name':'Complete native editions and historical/release qualification','outcome':'not_run','evidence':None}],
 next_step='Close non-text insertion and remaining responsive/property contracts, then installed controller/catalog/policy ownership, scene-aligned entry/restoration and independent escape. Continue all five release tracks.',
 limitations=['Owned Linux ext4/Xvfb/DBus evidence does not qualify installed editing or physical power-loss durability.', 'Provider discovery, non-text insertion, responsive/flow transforms, lock/visibility/typography, clipboard authority and recovery drafts remain required.', 'Full accessibility/performance, other adapters, historical laboratories and every complete-edition gate remain open.', 'Windows builds run on contemporary Windows; two existing symlink tooling assertions remain skipped.', 'The earlier isolated held-focus failure remains preserved; this checkpoint does not establish its original cause.'])
jsonschema.validate(h,json.loads((r/'spec/contracts/handoff.schema.json').read_bytes()));write(hp,h)
if pending:write(prefix+'staging.json',{'outcome':'pending'})
print('Prepared pending handoff.' if pending else 'Verified results and sealed handoff.')
