#include "editor_create_form.hpp"
#include "private_text.hpp"
#include <gtk/gtk.h>
namespace syspane::interfaces {
namespace {
void need(bool ok,const char* code){if(!ok)throw protocol::Error(code);}
std::string text(GtkWidget* w){GtkTextIter a,z;auto* b=gtk_text_view_get_buffer(GTK_TEXT_VIEW(w));gtk_text_buffer_get_bounds(b,&a,&z);auto* raw=gtk_text_buffer_get_text(b,&a,&z,FALSE);std::string out=raw;g_free(raw);return out;}
void text(GtkWidget* w,const std::string& value){gtk_text_buffer_set_text(gtk_text_view_get_buffer(GTK_TEXT_VIEW(w)),value.c_str(),static_cast<gint>(value.size()));}
void name(GtkWidget* w,const char* label,const std::string& id){atk_object_set_name(gtk_widget_get_accessible(w),label);atk_object_set_description(gtk_widget_get_accessible(w),("editor.create."+id).c_str());}
void wipe(GtkWidget* w){auto* m=gtk_combo_box_get_model(GTK_COMBO_BOX(w));GtkTreeIter i;if(gtk_tree_model_get_iter_first(m,&i))do{gtk_list_store_set(GTK_LIST_STORE(m),&i,0,"",-1);}while(gtk_tree_model_iter_next(m,&i));gtk_combo_box_text_remove_all(GTK_COMBO_BOX_TEXT(w));}
}
struct EditorCreateForm::Impl {
    GtkWidget *parent,*window,*box,*notebook,*error;std::map<std::string,GtkWidget*> fields,combos,sections;
    Json original;std::map<std::string,CreateInput> inputs;std::vector<std::optional<std::string>> parents;ContentChoices choices;std::string selected_kind;bool active=false,updating=false;
    std::function<bool(const CreateInput&)> apply;std::function<void(bool)> finished;std::function<void()> failed;
    void row(GtkWidget* into,const char* label,GtkWidget* w){auto* b=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,8);auto* l=gtk_label_new(label);gtk_label_set_xalign(GTK_LABEL(l),0);gtk_widget_set_size_request(l,145,-1);gtk_box_pack_start(GTK_BOX(b),l,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(b),w,TRUE,TRUE,0);gtk_box_pack_start(GTK_BOX(into),b,FALSE,FALSE,0);}
    void field(GtkWidget* into,const char* id,const char* label,unsigned limit=64,bool multiline=false){auto* w=private_text(limit,multiline);fields[id]=w;name(w,label,id);gtk_widget_set_size_request(w,320,multiline?65:25);row(into,label,w);}
    void combo(GtkWidget* into,const char* id,const char* label){auto* w=gtk_combo_box_text_new();combos[id]=w;name(w,label,id);row(into,label,w);}
    void button(GtkWidget* into,const char* id,const char* label){auto* w=gtk_button_new_with_label(label);name(w,label,id);gtk_box_pack_start(GTK_BOX(into),w,FALSE,FALSE,0);g_object_set_data_full(G_OBJECT(w),"create-action",g_strdup(id),g_free);g_signal_connect(w,"clicked",G_CALLBACK(+[](GtkWidget* w,gpointer p){auto& o=*static_cast<Impl*>(p);o.event([&]{const std::string id=static_cast<const char*>(g_object_get_data(G_OBJECT(w),"create-action"));if(id=="cancel")o.finish();else o.add();});}),this);}
    GtkWidget* section(GtkWidget* into,const char* id){auto* w=gtk_box_new(GTK_ORIENTATION_VERTICAL,5);gtk_box_pack_start(GTK_BOX(into),w,FALSE,FALSE,0);gtk_widget_set_no_show_all(w,TRUE);sections[id]=w;return w;}
    GtkWidget* page(const char* title){auto* w=gtk_box_new(GTK_ORIENTATION_VERTICAL,6);gtk_container_set_border_width(GTK_CONTAINER(w),8);gtk_notebook_append_page(GTK_NOTEBOOK(notebook),w,gtk_label_new(title));return w;}
    Impl(GtkWidget* p,std::function<bool(const CreateInput&)> a,std::function<void(bool)> f,std::function<void()> e):parent(p),apply(std::move(a)),finished(std::move(f)),failed(std::move(e)){
        window=gtk_window_new(GTK_WINDOW_TOPLEVEL);g_object_ref_sink(window);gtk_window_set_title(GTK_WINDOW(window),"SysPane Add Widget");gtk_window_set_modal(GTK_WINDOW(window),TRUE);gtk_window_set_resizable(GTK_WINDOW(window),FALSE);box=gtk_box_new(GTK_ORIENTATION_VERTICAL,6);gtk_container_set_border_width(GTK_CONTAINER(box),10);gtk_container_add(GTK_CONTAINER(window),box);
        combo(box,"kind","Widget kind");combo(box,"parent","Insert into");field(box,"title","Title",512);
        notebook=gtk_notebook_new();gtk_box_pack_start(GTK_BOX(box),notebook,TRUE,TRUE,0);auto* geometry=page("Placement");for(const char* id:{"x","y","width","height"})field(geometry,id,id);
        auto* content=page("Content");auto* body=section(content,"body");field(body,"body","Text / alternative text",1024,true);
        auto* source=section(content,"source");field(source,"entity_type","Entity type",256);field(source,"field","Value field",256);auto* second=section(content,"second");field(second,"second_field","Second column field",256);
        auto* asset=section(content,"asset");combo(asset,"asset","Image asset");
        auto* note=gtk_label_new("Sources start with this host's network counters. Use Bindings for filters or pins.");gtk_label_set_line_wrap(GTK_LABEL(note),TRUE);gtk_label_set_max_width_chars(GTK_LABEL(note),60);gtk_box_pack_start(GTK_BOX(content),note,FALSE,FALSE,0);
        error=gtk_label_new("");name(error,"","error");gtk_label_set_line_wrap(GTK_LABEL(error),TRUE);gtk_label_set_max_width_chars(GTK_LABEL(error),65);gtk_box_pack_start(GTK_BOX(box),error,FALSE,FALSE,0);
        auto* actions=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,5);gtk_box_pack_start(GTK_BOX(box),actions,FALSE,FALSE,0);button(actions,"add","Add widget");button(actions,"cancel","Cancel creation");
        g_signal_connect(combos.at("kind"),"changed",G_CALLBACK(+[](GtkComboBox*,gpointer p){auto& o=*static_cast<Impl*>(p);if(!o.updating)o.event([&]{o.save();o.selected_kind=o.chosen("kind");o.load();});}),this);
        g_signal_connect(window,"delete-event",G_CALLBACK(+[](GtkWidget*,GdkEvent*,gpointer p)->gboolean{auto& o=*static_cast<Impl*>(p);o.event([&]{o.finish();});return TRUE;}),this);
        g_signal_connect(window,"key-press-event",G_CALLBACK(+[](GtkWidget*,GdkEventKey* e,gpointer p)->gboolean{if(e->keyval!=GDK_KEY_Escape)return FALSE;auto& o=*static_cast<Impl*>(p);o.event([&]{o.finish();});return TRUE;}),this);
    }
    void options(const char* id,const std::vector<std::string>& values,int index){wipe(combos.at(id));for(const auto& v:values)gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(combos.at(id)),v.c_str());gtk_combo_box_set_active(GTK_COMBO_BOX(combos.at(id)),index);}
    std::string chosen(const char* id)const{auto* raw=gtk_combo_box_text_get_active_text(GTK_COMBO_BOX_TEXT(combos.at(id)));need(raw,"editor.create_choice");std::string out=raw;g_free(raw);return out;}
    void save(){if(selected_kind.empty())return;auto& input=inputs.at(selected_kind);for(const auto& f:fields)input.fields[f.first]=text(f.second);const int n=gtk_combo_box_get_active(GTK_COMBO_BOX(combos.at("asset")));input.asset=n>=0?choices.images.at(static_cast<std::size_t>(n)).value:Json();}
    void load(){updating=true;const auto& input=inputs.at(selected_kind);for(const auto& f:fields)text(f.second,input.fields.at(f.first));int asset=-1;for(std::size_t n=0;n<choices.images.size();++n)if(choices.images[n].value==input.asset)asset=static_cast<int>(n);gtk_combo_box_set_active(GTK_COMBO_BOX(combos.at("asset")),asset);
        for(const auto& section:sections){const auto& id=section.first;const bool show=(id=="body"&&(selected_kind=="text"||selected_kind=="image"))||(id=="source"&&(selected_kind=="value"||selected_kind=="status"||selected_kind=="table"||selected_kind=="chart"))||(id=="second"&&selected_kind=="table")||(id=="asset"&&selected_kind=="image");if(show){gtk_widget_set_no_show_all(section.second,FALSE);gtk_widget_show_all(section.second);gtk_widget_set_no_show_all(section.second,TRUE);}else gtk_widget_hide(section.second);}
        gtk_label_set_text(GTK_LABEL(error),"");updating=false;}
    void open(const Json& scene,const std::vector<std::string>& selection,ContentChoices resources){erase();updating=true;try{need(scene.at("schema_version")!="0.2.0","editor.create_version");original=scene;choices=std::move(resources);std::vector<std::string> kinds{"text","value","status","table","chart","image","group"};for(const auto& k:kinds)inputs.emplace(k,create_input(k));options("kind",kinds,0);selected_kind="text";
        std::vector<std::string> labels{"Scene roots"};parents.push_back(std::nullopt);int selected=0;for(const auto& w:scene.at("widgets"))if(w.at("kind")=="group"){parents.push_back(w.at("id").get<std::string>());labels.push_back(w.at("title").get<std::string>()+" ("+w.at("id").get<std::string>()+")");if(selection.size()==1&&selection[0]==w.at("id"))selected=static_cast<int>(parents.size())-1;}options("parent",labels,selected);
        labels.clear();for(const auto& image:choices.images)labels.push_back(image.label);options("asset",labels,-1);load();gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook),0);auto* top=gtk_widget_get_toplevel(parent);need(GTK_IS_WINDOW(top),"editor.create_parent");gtk_window_set_transient_for(GTK_WINDOW(window),GTK_WINDOW(top));gtk_window_set_position(GTK_WINDOW(window),GTK_WIN_POS_CENTER_ON_PARENT);active=true;updating=false;gtk_widget_show_all(window);gtk_window_present(GTK_WINDOW(window));}catch(...){erase();throw;}}
    void erase(){active=false;updating=true;for(const auto& f:fields)text(f.second,"");for(const auto& c:combos)wipe(c.second);gtk_label_set_text(GTK_LABEL(error),"");original=nullptr;inputs.clear();parents.clear();choices={};selected_kind.clear();gtk_widget_hide(window);updating=false;}
    void finish(bool changed=false){erase();auto* top=gtk_widget_get_toplevel(parent);if(GTK_IS_WINDOW(top))gtk_window_present(GTK_WINDOW(top));finished(changed);}
    void add(){save();const int n=gtk_combo_box_get_active(GTK_COMBO_BOX(combos.at("parent")));need(n>=0&&static_cast<std::size_t>(n)<parents.size(),"editor.parent");auto& input=inputs.at(selected_kind);input.parent=parents[static_cast<std::size_t>(n)];const bool changed=apply(input);finish(changed);}
    template<class F>void event(F f)noexcept{try{if(active)f();}catch(const protocol::Error& e){updating=false;const std::string code=e.what();gtk_label_set_text(GTK_LABEL(error),code=="editor.create_asset"?"Choose an admitted image asset before adding the widget.":code=="editor.create_columns"?"Table columns need different value fields.":code=="editor.content_number"||code=="editor.create_geometry"?"Enter finite geometry within the position and size limits.":"The widget could not be added. Check fields, scene limits, resources and current permissions.");}catch(...){erase();try{failed();}catch(...){}}}
    ~Impl(){erase();gtk_widget_destroy(window);g_object_unref(window);}
};
EditorCreateForm::EditorCreateForm(GtkWidget* p,std::function<bool(const CreateInput&)> a,std::function<void(bool)> f,std::function<void()> e):impl_(std::make_unique<Impl>(p,std::move(a),std::move(f),std::move(e))){}
EditorCreateForm::~EditorCreateForm()=default;void EditorCreateForm::open(const Json& scene,const std::vector<std::string>& selection,ContentChoices choices){impl_->open(scene,selection,std::move(choices));}void EditorCreateForm::erase(){impl_->erase();}bool EditorCreateForm::opened()const{return impl_->active;}
}
